### ISSUE TITLE
handlePart

### ISSUE THREAD

**Issue by wavded** [mjackson/mach#65]
@mjackson how would you suggest going about overwriting `handlePart` in `1.0`:

https://github.com/mjackson/mach/blob/091e000f766119bd36daf4f8d28fc19327abb123/modules/extensions/multipart.js#L62

If you recall, I wanted to add a hash to the upload in Mach when it was `>1.0` (see #23).  I want to do that again here.

**Comment by mjackson** [comment]
In 1.0 I introduced the concept of mach "extensions". Extensions are basically just functions that are used to extend the `mach` object and the core classes (i.e. `Connection`, `Message`, etc.). Extensions give us:

- the ability to specify only the features of mach that we need in our build, so we can have the smallest possible builds in browsers
- light-weight dependency injection (built on top of CommonJS, of course) so that e.g. extensions can depend on other extensions being loaded first
- a hook for users to create their own extensions for mach

@wavded In this case, I'd suggest you try creating a mach extension that overrides `Message#handlePart` for the case that you need. It will probably look something like this:

```js
var mach = require('mach');

function handlePartExtension(mach) {
  mach.Message.prototype.handlePart = function () {
    // your custom part-handling logic here
  };
}

mach.extend(handlePartExtension);
```

This is a new feature that I'm still putting a lot of work into (I was just working on it this morning) so please let me know how it goes. I'm pretty excited about it so far. It's working well and seems like an elegant solution to the problem of managing a large library like mach but only loading the pieces you need.

On a side note, I think extensions also address the issue that @abuchanan brought up in #29.
I'd suggest you try that approach if you want to override `handlePart`.

**Comment by mjackson** [comment]
@wavded Do you have any questions/suggestions/complaints here? I just pushed a bunch of commits that clean up some of the extensions, and added tests. Check out [how the server extension overrides the multipart extension's definition of `handlePart`](https://github.com/mjackson/mach/blob/8fecac88d6d08c793b6287911a66960ec0b840aa/modules/extensions/server.js#L211-L232).
